// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function XDeleteClient(arg1) {
  return window['go']['backend']['App']['XDeleteClient'](arg1);
}

export function XGetSymbolSettings(arg1) {
  return window['go']['backend']['App']['XGetSymbolSettings'](arg1);
}

export function XGetWsBasicInfo() {
  return window['go']['backend']['App']['XGetWsBasicInfo']();
}

export function XSaveSymbolSettings(arg1, arg2, arg3) {
  return window['go']['backend']['App']['XSaveSymbolSettings'](arg1, arg2, arg3);
}
