// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function XDeleteClient(arg1:string):Promise<void>;

export function XGetSymbolSettings(arg1:string):Promise<backend.StSocketClientSetting>;

export function XGetWsBasicInfo():Promise<backend.StWsBasicInfo>;

export function XSaveSymbolSettings(arg1:string,arg2:backend.StIndParam,arg3:backend.StPriceRange):Promise<boolean>;
